/**
 * generate-exercise-seed.ts
 *
 * Reads the @bryllim/workout-guide manifest (302 exercises, CC BY-SA 4.0) and
 * produces SQL INSERT statements for supabase/migrations/…_seed_exercise_catalog_v2.sql.
 *
 * Run once:
 *   pnpm tsx scripts/generate-exercise-seed.ts \
 *     > supabase/migrations/20260907130000_seed_exercise_catalog_v2.sql
 *
 * The 30 existing bootstrap rows (from seed_exercise_catalog_v1.sql) share the
 * same lower(name) with some package entries; ON CONFLICT … DO NOTHING skips them.
 * Their illustration_slug is already set by migration 20260907120000.
 */

import { exercises } from '@bryllim/workout-guide';
import type { Exercise } from '@bryllim/workout-guide';

// ── Enum mapping tables (docs/research-workout-guide.md §5) ──────────────────

type DbMuscle =
  | 'CHEST'
  | 'LATS'
  | 'UPPER_BACK'
  | 'LOWER_BACK'
  | 'SHOULDERS'
  | 'BICEPS'
  | 'TRICEPS'
  | 'QUADS'
  | 'HAMSTRINGS'
  | 'GLUTES'
  | 'CALVES'
  | 'CORE'
  | 'FULL_BODY'
  | 'CARDIO'
  | 'OTHER';

type DbEquipment =
  'BARBELL' | 'DUMBBELL' | 'MACHINE' | 'CABLE' | 'BODYWEIGHT' | 'KETTLEBELL' | 'BAND' | 'OTHER';

type DbMeasurement = 'WEIGHT_REPS' | 'REPS_ONLY' | 'DURATION' | 'BODYWEIGHT_ASSISTED';

const MUSCLE_MAP: Record<string, DbMuscle> = {
  Chest: 'CHEST',
  Lats: 'LATS',
  'Upper Back': 'UPPER_BACK',
  'Lower Back': 'LOWER_BACK',
  Shoulders: 'SHOULDERS',
  'Rear Delts': 'SHOULDERS',
  Biceps: 'BICEPS',
  Triceps: 'TRICEPS',
  Quads: 'QUADS',
  Hamstrings: 'HAMSTRINGS',
  Glutes: 'GLUTES',
  Calves: 'CALVES',
  Core: 'CORE',
  'Posterior Chain': 'FULL_BODY',
  Back: 'UPPER_BACK',
  Legs: 'QUADS',
  Adductors: 'OTHER',
  Forearms: 'OTHER',
  Hips: 'GLUTES',
  Mobility: 'OTHER',
};

const EQUIPMENT_MAP: Record<string, DbEquipment> = {
  Barbell: 'BARBELL',
  Dumbbell: 'DUMBBELL',
  Machine: 'MACHINE',
  Cable: 'CABLE',
  Bodyweight: 'BODYWEIGHT',
  Kettlebell: 'KETTLEBELL',
  'Resistance Band': 'BAND',
  'Pull-up Bar': 'BODYWEIGHT',
  Plate: 'OTHER',
  Bench: 'OTHER',
  Box: 'OTHER',
  'Stability Ball': 'OTHER',
  Chair: 'OTHER',
  Doorway: 'OTHER',
  Towel: 'OTHER',
  Wall: 'OTHER',
  Cardio: 'OTHER',
};

const MEASUREMENT_MAP: Record<string, DbMeasurement> = {
  weight_reps: 'WEIGHT_REPS',
  bodyweight_reps: 'REPS_ONLY',
  duration: 'DURATION',
  assisted_bodyweight: 'BODYWEIGHT_ASSISTED',
  distance_duration: 'DURATION',
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function mapMuscle(label: string): DbMuscle {
  const mapped = MUSCLE_MAP[label];
  if (!mapped) {
    process.stderr.write(`[WARN] Unknown primaryMuscle: "${label}" — falling back to OTHER\n`);
    return 'OTHER';
  }
  return mapped;
}

function mapEquipment(label: string): DbEquipment {
  const mapped = EQUIPMENT_MAP[label];
  if (!mapped) {
    process.stderr.write(`[WARN] Unknown equipment: "${label}" — falling back to OTHER\n`);
    return 'OTHER';
  }
  return mapped;
}

function mapMeasurement(type: string): DbMeasurement {
  const mapped = MEASUREMENT_MAP[type];
  if (!mapped) {
    process.stderr.write(`[WARN] Unknown exerciseType: "${type}" — falling back to REPS_ONLY\n`);
    return 'REPS_ONLY';
  }
  return mapped;
}

/** Escape a SQL string literal — single-quote any single quotes. */
function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Format an aliases array as a Postgres varchar[] literal, or NULL. */
function sqlAliases(aliases: string[]): string {
  if (aliases.length === 0) return 'null';
  const escaped = aliases.map((a) => `'${a.replace(/'/g, "''")}'`).join(', ');
  return `array[${escaped}]::varchar[]`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

function toRow(ex: Exercise): string {
  const name = sqlStr(ex.name);
  const muscle = mapMuscle(ex.primaryMuscle);
  const equipment = mapEquipment(ex.equipment);
  const measurement = mapMeasurement(ex.exerciseType);
  const slug = sqlStr(ex.slug);
  // Aliases: use secondaryMuscles as search hints in addition to the slug itself.
  // We keep aliases minimal — just the slug so search can find by it.
  const aliases = sqlAliases([ex.slug]);

  return (
    `  (gen_random_uuid(), ${name}, ${aliases}, ` +
    `'${muscle}', '${equipment}', '${measurement}', 'seed', ${slug}, true)`
  );
}

const header = `-- @bryllim/workout-guide@1.0.0 seed — 302 exercises (CC BY-SA 4.0).
-- Generated by scripts/generate-exercise-seed.ts. Do not edit by hand.
-- Attribution: Original exercise artwork by Everkinetic, expanded by Bryl Lim,
-- licensed under CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>.
--
-- ON CONFLICT skips the 30 bootstrap rows already inserted in seed_exercise_catalog_v1.sql.
-- Their illustration_slug is set by migration 20260907120000_exercise_illustration_slug.sql.

insert into public.exercise_items (
  id, name, aliases, primary_muscle, equipment, measurement, source, illustration_slug, active
)
values
`;

const rows = exercises.map(toRow).join(',\n');

const footer = `
on conflict (lower(name)) where source = 'seed' and deleted_at is null do nothing;
`;

process.stdout.write(header + rows + footer);
process.stderr.write(`[INFO] Generated ${exercises.length} exercise rows.\n`);
